package in.election.entity;

public enum AuditAction {
    CREATE, UPDATE, DELETE, LOGIN, LOGOUT, VOTE_CAST,
    ELIGIBILITY_CHECK, ELECTION_START, ELECTION_END,
    CANDIDATE_REGISTER, VOTER_REGISTER, VIEW, SEARCH
}
